### ISSUE TITLE
odd character

### ISSUE THREAD

**Issue by lovettchris** [leanprover/fp-lean#10]
This "outputs" block in [Functions and Definitions](file:///D:/Temp/lean/fp-lean-2022-05-05/html/getting-to-know/functions-and-definitions.html) has an odd character prefix "🛈 "

outputs
🛈 "Hello Lean"

I believe it's coming from this CSS, but none of the other outputs listed have this prefix:
```css
code.info::before {
    content: "🛈 ";
    font-style: normal;
}
```
